### ISSUE TITLE
SQLException: Invalid character in connection string.

### ISSUE THREAD

**Issue by jakobbraun** [exasol/exasol-testcontainers#180]
I just got the following exception when starting exasol-testcontainers:

```
java.sql.SQLException: Invalid character in connection string.

	at com.exasol.jdbc.EXADriver.parseURL8(EXADriver.java:570)
	at com.exasol.jdbc.EXADriver.connect(EXADriver.java:172)
	at com.exasol.containers.ExasolContainer.createConnectionForUser(ExasolContainer.java:335)
	at com.exasol.containers.ExasolContainer.createConnection(ExasolContainer.java:345)
```

**Comment by jakobbraun** [comment]
on second run (with reuse) I got:
```
Caused by: org.testcontainers.containers.ContainerLaunchException: F-ETC-5: Exasol container start-up timed out trying connection to 'jdbc:exa:localhost/ec3be8628f3939cc979928b3304f598212bf05878e916c15b7c8c2694fa7fc50:49354;validateservercertificate=1' using query 'SELECT 1 FROM DUAL' after '362.2' seconds. Last connection exception was: 'Could not create new connection'
	at com.exasol.containers.ExasolContainer.waitUntilStatementCanBeExecuted(ExasolContainer.java:628)
	at com.exasol.containers.ExasolContainer.waitUntilContainerStarted(ExasolContainer.java:487)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:468)
```

**Comment by jakobbraun** [comment]
I could also reproduce it with a fresh start.

**Comment by jakobbraun** [comment]
username and password are default ones. --> probably don't cause the problem

**Comment by jakobbraun** [comment]
Maybe it's an issue with the fingerprint...

**Comment by jakobbraun** [comment]
Example fingerprint for which it failed: `3419432574666ff70eef6b9f54c6e81affe3a8d6c9102d201948ba23eea07393`

**Comment by jakobbraun** [comment]
The issue occurs when a different dependency uses an older version of the exasol jdbc driver.

Idea for a fix:
Test at runtime if the JDBC driver is new enough. It contains a method for getting the version number.

**Comment by kaklakariada** [comment]
Another idea to fix this: specify fingerprint in URL not after hostname `jdbc:exa:<host>/<fingerprint>:<port>` but as argument:

`jdbc:exa:<host>:<port>;fingerprint=<fingerprint>`

Older drivers should ignore the unknown argument.
