### ISSUE TITLE
Startup fails when target directory does not exist

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-testcontainers#206]
Startup fails when `target` directory does not exist.
This happens for example for non-java projects.
Proposal: 
1. exasol-testcontainers should create the folder if missing. 
2. user (other project) must / can configure the path to the file

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
        at com.exasol.containers.ExasolContainer.start(ExasolContainer.java:509)
        at com.exasol.exasoltestsetup.testcontainers.ExasolTestcontainerTestSetup.<init>(ExasolTestcontainerTestSetup.java:34)
        at com.exasol.exasoltestsetup.ExasolTestSetupFactory.getTestSetup(ExasolTestSetupFactory.java:48)
        at com.exasol.testsetupabstraction.server.Main.main(Main.java:37)
Caused by: com.exasol.containers.ExasolContainerInitializationException: Could not create SSH key pair
        at com.exasol.containers.ExasolContainer.getSshKeys(ExasolContainer.java:999)
        at com.exasol.containers.ExasolContainer.createDockerAccess(ExasolContainer.java:985)
        at com.exasol.containers.ExasolContainer.configure(ExasolContainer.java:186)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:327)
        ... 5 more
Caused by: java.nio.file.NoSuchFileException: target/id_rsa
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
        at com.exasol.containers.ssh.SshKeys$Builder.writeToFiles(SshKeys.java:121)
        at com.exasol.containers.ssh.SshKeys$Builder.createKeyPair(SshKeys.java:111)
        at com.exasol.containers.ssh.SshKeys$Builder.build(SshKeys.java:104)
        at com.exasol.containers.ExasolContainer.getSshKeys(ExasolContainer.java:997)
        ... 8 more
```

### Workaround
Create the `target` directory before starting exasol-testcontainers.

**Comment by redcatbear** [comment]
I like the automatism better. Main problem is that Gradle Projects don't have `target` directories. It's called `build`, so this approach is only compatible with Maven. Sure, you can create a `target` directory in a Gradle project. But it should not exist. For now I will just create the missing target directory.
