### ISSUE TITLE
NullPointerException in getJdbcConnection

### ISSUE THREAD

**Issue by exaSR** [exasol/exasol-testcontainers#36]
When the container has not been started yet, a call to `getJdbcUrl()` ends up like this:

```
java.lang.NullPointerException
	at org.testcontainers.DockerClientFactory.dockerHostIpAddress(DockerClientFactory.java:240)
	at org.testcontainers.containers.ContainerState.getContainerIpAddress(ContainerState.java:29)
	at com.exasol.containers.ExasolContainer.getJdbcUrl(ExasolContainer.java:80)

```

Any other Exception or NULL would be fine :)

**Comment by bsideup** [comment]
Please try Testcontainers  v1.12.5 (there was a regression in 1.12.4), it shouldn't throw an NPE anymore.

See https://github.com/testcontainers/testcontainers-java/pull/2119

**Comment by redcatbear** [comment]
Thanks for the information @bsideup. Next release of the `exaso-testcontainers` will be based on 1.12.5.
