### ISSUE TITLE
EXAoperation Plugin installation fails on Windows

### ISSUE THREAD

**Issue by exaSR** [exasol/exasol-testcontainers#48]
It looks like `ExaOperationEmulator` is passing windows paths ("java.io.tmpdir") to tar inside the docker container:

```java
    private static final String TMP_DIRECTORY = System.getProperty("java.io.tmpdir");
...
        final String from = TMP_DIRECTORY + "/" + plugin.getFileName();
        final String to = TMP_DIRECTORY + "/";
...
            final ExecResult unpackOuterResult = this.container.execInContainer("tar", "xf", from, "-C", to);
```

**Comment by exaSR** [comment]
```none
Mar 19, 2020 12:26:26 PM com.exasol.exaoperation.ExaOperationEmulator installPluginPackage
INFO: Installing plug-in "src\test\sh\Plugin.Testing.Stub-1.0.0-2020-02-02.pkg".


com.exasol.exaoperation.ExaOperationEmulatorException: Failed to unpack plug-in package (outer TAR archive).
Cause: tar: Cannot connect to C: resolve failed


	at com.exasol.exaoperation.ExaOperationEmulator.extractPluginPackage(ExaOperationEmulator.java:67)
	at com.exasol.exaoperation.ExaOperationEmulator.installPluginPackage(ExaOperationEmulator.java:44)
	at com.exasol.exaoperation.ExaOperationEmulatorIT.testInstallPluginPackage(ExaOperationEmulatorIT.java:42)
```
