### ISSUE TITLE
 Bucket "default" does not exist in configuration exception

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/exasol-testcontainers#52]
## Situation

I use `exasol-testcontainers` for integration testing and run build on Travis. Sometimes builds randomly fail with the following exception:

```
20/03/26 10:13:11 INFO 4]: Container localstack/localstack:0.9.4 is starting: d16663adf073d571ab5f50ce782684a44da40ef52b456f7e823cc22164eeee0a
20/03/26 10:13:23 INFO 4]: Container localstack/localstack:0.9.4 started in PT14.395844S
[info] com.exasol.cloudetl.kinesis.KinesisImportQueryGeneratorIT *** ABORTED ***
[info]   java.lang.IllegalArgumentException: Bucket "default" does not exist in configuration
[info]   at com.exasol.config.BucketFsServiceConfiguration.getBucketConfiguration(BucketFsServiceConfiguration.java:59)
[info]   at com.exasol.bucketfs.BucketFactory.getBucket(BucketFactory.java:50)
[info]   at com.exasol.containers.ExasolContainer.getBucket(ExasolContainer.java:202)
[info]   at com.exasol.containers.ExasolContainer.getDefaultBucket(ExasolContainer.java:219)
[info]   at com.exasol.cloudetl.kinesis.KinesisAbstractIntegrationTest.uploadJarToBucket(KinesisAbstractIntegrationTest.scala:62)
[info]   at com.exasol.cloudetl.kinesis.KinesisAbstractIntegrationTest.setupExasol(KinesisAbstractIntegrationTest.scala:54)
[info]   at com.exasol.cloudetl.kinesis.KinesisAbstractIntegrationTest.setupExasol$(KinesisAbstractIntegrationTest.scala:52)
[info]   at com.exasol.cloudetl.kinesis.KinesisImportQueryGeneratorIT.setupExasol(KinesisImportQueryGeneratorIT.scala:6)
[info]   at com.exasol.cloudetl.kinesis.KinesisImportQueryGeneratorIT.beforeAll(KinesisImportQueryGeneratorIT.scala:13)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   ...
```

**Comment by morazow** [comment]
For me this seems like the BucketFs or default bucket is not ready when trying to upload. One approach, as a user of test-containers, is to try at least three uploads with a back-off before failing.

**Comment by exaSR** [comment]
Sounds to me like the testcontainers should do that before signaling "startup complete" to the user :)

**Comment by redcatbear** [comment]
Exactly. There is a waiting strategy implemented at the moment already before the bucket configuration is read. Seems it is still not strict enough.

**Comment by redcatbear** [comment]
I will take care of this. I take this bug personal. :-)

**Comment by redcatbear** [comment]
This bug has not surfaced in a while. I am guessing that it was fixed in the course of the various improvements of startup service monitoring.
