### ISSUE TITLE
getDefaultBucket() failes if explicit port mapping was defined

### ISSUE THREAD

**Issue by jakobbraun** [exasol/exasol-testcontainers#76]
Steps to reproduce:
```
@Container
private static final ExasolContainer<? extends ExasolContainer<?>> container = new ExasolContainer<>()
            .withExposedPorts(8888).withLogConsumer(new Slf4jLogConsumer(LOGGER)).withReuse(true);

@BeforeAll
static void beforeAll(){
  container.getDefaultBucket();
}
```

```
java.lang.NullPointerException
	at com.exasol.bucketfs.BucketFactory.mapPort(BucketFactory.java:36)
	at com.exasol.bucketfs.BucketFactory.getBucket(BucketFactory.java:59)
	at com.exasol.containers.ExasolContainer.getBucket(ExasolContainer.java:245)
	at com.exasol.containers.ExasolContainer.getDefaultBucket(ExasolContainer.java:262)
```

**Comment by jakobbraun** [comment]
This behavior is intended. If withExposedPorts is called explicitely, database and bucketfs must be exposed, otherwise internal stuff will break.
