### ISSUE TITLE
Regression: Container fails to start on Windows

### ISSUE THREAD

**Issue by exaSR** [exasol/exasol-testcontainers#81]
## Container creation code
```java
 ExasolContainer<? extends ExasolContainer<?>> db_1 = new ExasolContainer<>( getDockerVersionFor( DataBase.DATABASE_1 ) ).withRequiredServices();

// not the database port
    db_1.addExposedPort( getServicePort() );
    db_1.start();
```

## Output with exasol-testcontainers-2.0.0
```
2020-09-23 10:42:39.731 [INFO   ] Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first 
2020-09-23 10:42:40.566 [INFO   ] Accessing docker with local Npipe socket (npipe:////./pipe/docker_engine) 
2020-09-23 10:42:40.567 [INFO   ] Found Docker environment with local Npipe socket (npipe:////./pipe/docker_engine) 
2020-09-23 10:42:40.825 [INFO   ] Docker host IP address is localhost 
2020-09-23 10:42:40.880 [INFO   ] Connected to docker: 
  Server Version: 19.03.12
  API Version: 1.40
  Operating System: Docker Desktop
  Total Memory: 25563 MB 
2020-09-23 10:42:41.390 [INFO   ] Credential helper/store (docker-credential-desktop) does not have credentials for quay.io 
2020-09-23 10:42:42.082 [INFO   ] Ryuk started - will monitor and terminate Testcontainers containers on JVM exit 
2020-09-23 10:42:42.083 [INFO   ] Checking the system... 
2020-09-23 10:42:42.084 [INFO   ] ?? Docker server version should be at least 1.6.0 
2020-09-23 10:42:42.204 [INFO   ] ?? Docker environment should have more than 2GB free disk space 
2020-09-23 10:42:42.221 [INFO   ] Creating container for image: exasol/docker-db:6.2.4-d1 
2020-09-23 10:42:42.406 [INFO   ] Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io 
2020-09-23 10:42:42.469 [INFO   ] Starting container with ID: f0ca3224ccb92b68a46f2f1d6d869e29ed6910c229c63c8e61f961112c5e0f65 
2020-09-23 10:42:42.806 [INFO   ] Container exasol/docker-db:6.2.4-d1 is starting: f0ca3224ccb92b68a46f2f1d6d869e29ed6910c229c63c8e61f961112c5e0f65 
2020-09-23 10:42:42.821 [INFO   ] Waiting for cluster configuration to become available. 
2020-09-23 10:42:43.516 [INFO   ] Reading cluster configuration from "/exa/etc/EXAConf" 
2020-09-23 10:42:43.619 [INFO   ] Waiting for database connection to become available at jdbc:exa:localhost:32788 using query 'SELECT 1 FROM DUAL' 
2020-09-23 10:43:40.398 [INFO   ] Container is started (JDBC URL: jdbc:exa:localhost:32788) 
2020-09-23 10:43:40.399 [INFO   ] Container exasol/docker-db:6.2.4-d1 started in PT1M0.7086049S 
```

## Output with 3.0.0
```
2020-09-23 10:53:50.867 [INFO   ] Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first 
2020-09-23 10:53:51.770 [INFO   ] Accessing docker with local Npipe socket (npipe:////./pipe/docker_engine) 
2020-09-23 10:53:51.771 [INFO   ] Found Docker environment with local Npipe socket (npipe:////./pipe/docker_engine) 
2020-09-23 10:53:52.110 [INFO   ] Docker host IP address is localhost 
2020-09-23 10:53:52.161 [INFO   ] Connected to docker: 
  Server Version: 19.03.12
  API Version: 1.40
  Operating System: Docker Desktop
  Total Memory: 25563 MB 
2020-09-23 10:53:52.801 [INFO   ] Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io 
2020-09-23 10:53:53.631 [INFO   ] Ryuk started - will monitor and terminate Testcontainers containers on JVM exit 
2020-09-23 10:53:53.632 [INFO   ] Checking the system... 
2020-09-23 10:53:53.634 [INFO   ] ?? Docker server version should be at least 1.6.0 
2020-09-23 10:53:53.762 [INFO   ] ?? Docker environment should have more than 2GB free disk space 
2020-09-23 10:53:53.780 [INFO   ] Creating container for image: exasol/docker-db:6.2.4-d1 
2020-09-23 10:53:53.849 [INFO   ] Starting container with ID: 027beeb79568227f8a95e151447bc8c5ff854dfcdad14e749d7dac495f1f90e6 
2020-09-23 10:53:54.230 [INFO   ] Container exasol/docker-db:6.2.4-d1 is starting: 027beeb79568227f8a95e151447bc8c5ff854dfcdad14e749d7dac495f1f90e6 
2020-09-23 10:53:55.549 [SEVERE ] Could not start container 
2020-09-23 10:53:55.614 [SEVERE ] Log output from the failed container:
[2020-09-23 08:53:54] exadt:: '/exa/etc' does not exist! Doing full initialization.

[2020-09-23 08:53:54] exadt:: searching for the first interface with state UP

[2020-09-23 08:53:54] exadt:: copying license file ''/.license.xml'' to ''/exa/etc/license.xml''

[2020-09-23 08:53:54] exadt:: initializing EXAConf

[2020-09-23 08:53:54] exadt:: using interface 'eth0@if41' with address '172.17.0.3/16'.

[2020-09-23 08:53:54] exadt:: setting hostname to 'n11'

[2020-09-23 08:53:54] exadt:: creating EXAStorage devices

[2020-09-23 08:53:54] exadt:: changing file ownership to 500:500

[2020-09-23 08:53:54] exadt:: calling '('/usr/opt/EXASuite-6/EXARuntime-6.2.4/bin/numactl', ['--interleave=all', '/usr/opt/EXASuite-6/EXAClusterOS-6.2.4/libexec/exainit.py'])'
 


org.testcontainers.containers.ContainerLaunchException: Container startup failed

	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at com.exasol.containertest.workflow_docker.DockerContainerBase.setupCluster(DockerContainerBase.java:119)
	at com.exasol.containertest.AbstractTestWorkflow.setup(AbstractTestWorkflow.java:261)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:205)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:201)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	... 66 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:498)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 67 more
Caused by: java.lang.IllegalArgumentException: Requested port (8888) is not mapped
	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:152)
	at com.exasol.containers.ExasolContainer.getJdbcUrl(ExasolContainer.java:125)
	at org.testcontainers.containers.JdbcDatabaseContainer.constructUrlForConnection(JdbcDatabaseContainer.java:233)
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:199)
	at com.exasol.containers.ExasolContainer.isConnectionAvailable(ExasolContainer.java:386)
	at com.exasol.containers.ExasolContainer.waitUntilStatementCanBeExecuted(ExasolContainer.java:369)
	at com.exasol.containers.ExasolContainer.waitUntilContainerStarted(ExasolContainer.java:294)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441)
	... 69 more
```

**Comment by exaSR** [comment]
Verified the container still starts with version 2.0.2

**Comment by jakobbraun** [comment]
Probably same issue as https://github.com/exasol/exasol-testcontainers/issues/76

**Comment by exaSR** [comment]
@jakobbraun : Confirmed that the problem is using `addExposedPort`.
As the method is called **ADD** I was not expecting it to actually prevent exposing the regular database port in the new release.

**Comment by jakobbraun** [comment]
Extracted issue: https://github.com/exasol/exasol-testcontainers/issues/82
